### PR TITLE
Fix URL for packaging guidelines

### PR DESCRIPTION
**Pull request by ggvl**
This patch fix some bad URL in documentation.md

### CODE REVIEW

**Comment by ggvl** [comment]
@m-blaha

**Comment by ggvl** [comment]
@xsuchy

**Review by xsuchy — APPROVED** [review]

**Comment by ggvl** [comment]
@dmnks need review, thanks.

**Comment by pmatilai** [comment]
This replaces a bunch of dead links with links to something completely different.
Adding a link to Fedora Packaging Guidelines would be fine, but the RPM Guide these links to is/was more like an rpm reference manual and not packaging guidelines. In particular, you can't replace "programming rpm with language X" with links to *packaging* software written in language X.

**Pull request closed without merging**
